# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 341)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ui_check_count = QtWidgets.QLineEdit(self.centralwidget)
        self.ui_check_count.setGeometry(QtCore.QRect(230, 10, 41, 21))
        self.ui_check_count.setObjectName("ui_check_count")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ui_start = QtWidgets.QPushButton(self.centralwidget)
        self.ui_start.setGeometry(QtCore.QRect(100, 110, 75, 31))
        self.ui_start.setObjectName("ui_start")
        self.ui_showstat = QtWidgets.QPushButton(self.centralwidget)
        self.ui_showstat.setGeometry(QtCore.QRect(710, 270, 75, 23))
        self.ui_showstat.setObjectName("ui_showstat")
        self.ui_savestat = QtWidgets.QPushButton(self.centralwidget)
        self.ui_savestat.setGeometry(QtCore.QRect(620, 270, 75, 23))
        self.ui_savestat.setObjectName("ui_savestat")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ui_player1_type = QtWidgets.QComboBox(self.centralwidget)
        self.ui_player1_type.setGeometry(QtCore.QRect(90, 40, 181, 22))
        self.ui_player1_type.setObjectName("ui_player1_type")
        self.ui_player1_type.addItem("")
        self.ui_player1_type.addItem("")
        self.ui_player1_type.addItem("")
        self.ui_player2_type = QtWidgets.QComboBox(self.centralwidget)
        self.ui_player2_type.setGeometry(QtCore.QRect(90, 70, 181, 22))
        self.ui_player2_type.setObjectName("ui_player2_type")
        self.ui_player2_type.addItem("")
        self.ui_player2_type.addItem("")
        self.ui_player2_type.addItem("")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 160, 261, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ui_player1_checks = QtWidgets.QComboBox(self.centralwidget)
        self.ui_player1_checks.setGeometry(QtCore.QRect(90, 180, 69, 22))
        self.ui_player1_checks.setObjectName("ui_player1_checks")
        self.ui_player1_move = QtWidgets.QPushButton(self.centralwidget)
        self.ui_player1_move.setGeometry(QtCore.QRect(170, 180, 101, 23))
        self.ui_player1_move.setObjectName("ui_player1_move")
        self.ui_player2_move = QtWidgets.QPushButton(self.centralwidget)
        self.ui_player2_move.setGeometry(QtCore.QRect(170, 220, 101, 23))
        self.ui_player2_move.setObjectName("ui_player2_move")
        self.ui_player2_checks = QtWidgets.QComboBox(self.centralwidget)
        self.ui_player2_checks.setGeometry(QtCore.QRect(90, 220, 69, 22))
        self.ui_player2_checks.setObjectName("ui_player2_checks")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 250, 771, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ui_log = QtWidgets.QTextEdit(self.centralwidget)
        self.ui_log.setGeometry(QtCore.QRect(280, 10, 501, 231))
        self.ui_log.setLineWrapColumnOrWidth(2)
        self.ui_log.setReadOnly(True)
        self.ui_log.setObjectName("ui_log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ui_check_count.setText(_translate("MainWindow", "6"))
        self.label.setText(_translate("MainWindow", "По сколько фишек раздаём?"))
        self.ui_start.setText(_translate("MainWindow", "Начать"))
        self.ui_showstat.setText(_translate("MainWindow", "Статистика"))
        self.ui_savestat.setText(_translate("MainWindow", "Сохранить"))
        self.label_2.setText(_translate("MainWindow", "Игрок #1"))
        self.label_3.setText(_translate("MainWindow", "Игрок #2"))
        self.ui_player1_type.setItemText(0, _translate("MainWindow", "Человек"))
        self.ui_player1_type.setItemText(1, _translate("MainWindow", "Компьютер (тактика)"))
        self.ui_player1_type.setItemText(2, _translate("MainWindow", "Компьютер (рандом)"))
        self.ui_player2_type.setItemText(0, _translate("MainWindow", "Человек"))
        self.ui_player2_type.setItemText(1, _translate("MainWindow", "Компьютер (тактика)"))
        self.ui_player2_type.setItemText(2, _translate("MainWindow", "Компьютер (рандом)"))
        self.label_5.setText(_translate("MainWindow", "Игрок #1"))
        self.ui_player1_move.setText(_translate("MainWindow", "Ходить"))
        self.ui_player2_move.setText(_translate("MainWindow", "Ходить"))
        self.label_6.setText(_translate("MainWindow", "Игрок #1"))

